---
  # Title: app-citrix-receiver-13.9.1
  #
  # Auhtor: Luc Rutten
  # Version: 1.0
  # File: task/main.yml
  #
  # Description:
  #   Installation of Citrix Receiver on Ubuntu

  - name: "Enable i386 Multiarch"
    command: dpkg --add-architecture i386
    when: ansible_architecture != 'i386'

  - name: "Update reposities"
    apt:
      update_cache: yes

  - name: "Download Files"
    get_url:
      url: "{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items:
      - { src: '{{ resource_url_receiver }}', dest: '/tmp/' }
      - { src: '{{ resource_url_receiver_web }}', dest: '/tmp/' }
      - { src: '{{ resource_url_receiver_usb }}', dest: '/tmp/' }

  - name: "Install DEB packages"
    apt:
      deb: "{{ item }}"
      state: "{{ deb_state }}"
    with_items:
      - "/tmp/{{ deb_receiver }}"
      - "/tmp/{{ deb_receiver_web }}"
      - "/tmp/{{ deb_receiver_usb }}"
    
  - name: "Add SSL Certificates for Citrix receiver"
    file:
      src: /usr/share/ca-certificates/mozilla/*
      dest: /opt/Citrix/ICAClient/keystore/cacerts/


