---
  # Title: app-citrix-receiver-13.9.1
  #
  # Auhtor: Luc Rutten
  # Version: 1.0
  # File: task/main.yml
  #
  # Description:
  #   Installation of Citrix Receiver on Ubuntu
  # 
  # Note by David omdat er standaard geen firefox geinstalleerd wordt op de endpoints heb ik de SSL certificaten voor de citrix receiver geuncomment. 
  #  Deze zijn tevens momenteel nog niet benodigd, voor de ICA sessie naar xenapp servers.


  - name: "For OS: Ubuntu 18.04LTS, Arch: amd64"
    import_tasks: ubuntu-1804-amd64.yml
    when:
      - ansible_distribution_version == "18.04"
      - ansible_architecture == "x86_64"
 
  - name: "Import xubuntu-core-networkmanager template (change to xubuntu networkmanager)"
    import_tasks: ubt-1804-add-ssl-certificates.yml
   

