---
  # Title: app-citrix-receiver-13.9.1
  #
  # Auhtor: Luc Rutten
  # Version: 1.0
  # File: task/main.yml
  #
  # Description:
  #   Installation of Citrix Receiver on Ubuntu
  # 
  #Note by David omdat er standaard geen firefox geinstalleerd wordt op de endpoints heb ik de SSL certificaten voor de citrix receiver geuncomment. 
  #  Deze zijn tevens momenteel nog niet benodigd, voor de ICA sessie naar xenapp servers.


  - name: "check if citrix receiver is already installed, if not found skipping...."
    stat:
      path: /opt/Citrix/ICAClient
    register: citrix_active

  - name: "Enable i386 Multiarch"
    command: dpkg --add-architecture i386
    when: ansible_architecture != 'i386'

  - name: "Update reposities"
    apt:
      update_cache: yes
    when: citrix_active.stat.exists == False

  - name: "Download Files"
    get_url:
      url: "{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items:
      - { src: '{{ resource_url_receiver }}', dest: '/tmp/' }
      - { src: '{{ resource_url_receiver_web }}', dest: '/tmp/' }
      - { src: '{{ resource_url_receiver_usb }}', dest: '/tmp/' }
    when: citrix_active.stat.exists == False

  - name: "Install DEB packages"
    apt:
      deb: "{{ item }}"
      state: "{{ deb_state }}"
    with_items:
      - "/tmp/{{ deb_receiver }}"
      - "/tmp/{{ deb_receiver_web }}"
      - "/tmp/{{ deb_receiver_usb }}"
    when: citrix_active.stat.exists == False

  - name: "load in template citrix store"
    template:
      src: StoreCache.ctx.j2
      dest: /opt/Citrix/ICAClient/config/StoreCache.ctx-template
  
  - name: "load in crontab template"
    template:
      src: citrixremove.j2
      dest: /opt/Citrix/citrixremove.sh
      mode: 0744
  
  - name: "create a crontab that runs every 5 minutes 5 0 * * * using the root user, for removing background citrix receiver processes"
    cron: 
      name: "remove-background-processes-Citrix"
      minute: "*/5"
      user: root
      job: /opt/Citrix/citrixremove.sh >/dev/null 2>&1

  - name: "Import xubuntu-core-networkmanager template (change to xubuntu networkmanager)"
    import_tasks: ubt-1804-add-ssl-certificates.yml

